CREATE TABLE rollplay_topics (
  topic_id INTEGER PRIMARY KEY GENERATED BY default AS IDENTITY,
  title TEXT,
  topic_desc TEXT,
  rpg_system TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  topic_owner INTEGER
);


  -- topicOwner TEXT REFERENCES rollplay_users(userId)