CREATE TABLE rollplay_comments (
  comment_id INTEGER PRIMARY KEY GENERATED BY default AS IDENTITY,
  comment_desc TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
  comment_thread INTEGER,
  comment_owner INTEGER
);